---
cassandra:
  nodes:
    - node0
    - node1
    - node2
  port: 9042
  keyspace: vtsil

kafka:
  servers:
    - node0
    - node1
    - node2
  consumer_psd:
    group: 'psd'
    offset: 'earliest'
    topic:
      - 'rawData_1'
      - 'rawData_2'
      - 'rawData_3'
      - 'rawData_4'
      - 'rawData_5'
  producer_h5:
    retries: 2
    max_in_flight: 1
    linger_ms: 100
  consumer_h5:
    group: 'filesync'
    offset: 'earliest'
    topic: incomingFiles
  producer_hdfs:
    retries: 2
    max_in_flight: 1
  consumer_hdfs:
    group: 'hdfs'
    offset: 'earliest'
    topic: 'putHdfs'

file_sync:
  remote_folder: 'data'
  temp_file_path: '/home/vtsil/vtsil-data-viz-api/datavizapi/scripts/.lastread'
  credentials_file_path: '/home/vtsil/vtsil-data-viz-api/datavizapi/scripts/.credentials'
  destination_dir: '/home/vtsil/vtsil-data-viz-api/datavizapi/scripts'
  file_name_format: '%Y-%m-%d_%H_%M_%S'
  ftp_remote_ip: '10.0.1.8'
  ftp_remote_port: '8000'

footstep_sensor_names: ['3C-19', '3C-20', '3C-21', '3C-22', '3C-23', '3C-24', '3C-25', '3C-26', '3C-27', '3C-28', '3C-29', '3C-30']
...